get:
  tags:
    - environment-variables
  summary: Get All Environment Variables
  description: Returns all environment variables associated with an environment.
  operationId: getConfigV01EnvironmentVariables
  parameters:
    - name: page
      in: query
      description: 0-based page number.
      schema:
        type: integer
        format: int32
        default: 0
    - name: page_size
      in: query
      description: >-
        Number of results per page. Valid values are: 1 - 100. **Default
        value:** 20
      schema:
        type: integer
        format: int32
        default: 20
    - name: key
      in: query
      description: Find environment variable by their key
      schema:
        type: string
    - name: environment_id
      in: query
      required: true
      schema:
        type: string
  responses:
    '200':
      description: Returns all environment variables associated with an environment.
      content:
        application/json:
          schema:
            $ref: >-
              ../components/schemas/Config_V1_Entities_EnvironmentVariable_Collection.yaml
    '400':
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: ../components/schemas/BaseApi_Entities_UserError.yaml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../components/schemas/BaseApi_Entities_GeneralError.yaml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../components/schemas/BaseApi_Entities_GeneralError.yaml
    '404':
      description: Not Found
      content:
        application/json:
          schema:
            $ref: ../components/schemas/BaseApi_Entities_GeneralError.yaml
    '500':
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: ../components/schemas/BaseApi_Entities_GeneralError.yaml
put:
  tags:
    - environment-variables
  summary: Create or Replace Environment Variable
  description: Create or replace an environment variable.
  operationId: putConfigV01EnvironmentVariables
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/putConfigV01EnvironmentVariables.yaml
    required: true
  responses:
    '200':
      description: Create or replace an environment variable.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Config_V1_Entities_EnvironmentVariable.yaml
    '400':
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: ../components/schemas/BaseApi_Entities_UserError.yaml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../components/schemas/BaseApi_Entities_GeneralError.yaml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../components/schemas/BaseApi_Entities_GeneralError.yaml
    '404':
      description: Not Found
      content:
        application/json:
          schema:
            $ref: ../components/schemas/BaseApi_Entities_GeneralError.yaml
    '500':
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: ../components/schemas/BaseApi_Entities_GeneralError.yaml
  x-codegen-request-body-name: putConfigV01EnvironmentVariables
