put:
  summary: Set Environment Redirect
  description: Creates or updates an environment redirect.
  parameters:
    - in: String
      name: from
      description: The path where to redirect from.
      required: true
      schema:
        type: string
    - in: String
      name: to
      description: The path where to redirect to.
      required: true
      schema:
        type: string
    - in: Integer
      name: status
      description: 'Redirect status code: 301, 302, 307, 308.'
      required: false
      schema:
        type: integer
        format: int32
    - in: Boolean
      name: forward_query_string
      description: Determines whether to forward query string to redirect location.
      required: false
      schema:
        type: boolean
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/putConfigV01EnvironmentRedirects.yaml
    required: true
  security:
    - configScope:
        - app.config
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Config_V1_Entities_EnvironmentRedirect.yaml
    '400':
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: ../components/schemas/BaseApi_Entities_UserError.yaml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../components/schemas/BaseApi_Entities_GeneralError.yaml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../components/schemas/BaseApi_Entities_GeneralError.yaml
    '404':
      description: Not Found
      content:
        application/json:
          schema:
            $ref: ../components/schemas/BaseApi_Entities_GeneralError.yaml
    '429':
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: ../components/schemas/BaseApi_Entities_GeneralError.yaml
    '500':
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: ../components/schemas/BaseApi_Entities_GeneralError.yaml
  tags:
    - environment-redirects
  operationId: putConfigV01EnvironmentRedirects
get:
  summary: Get All Environment Redirects
  description: Returns all redirects associated with an environment.
  parameters:
    - in: query
      name: page
      description: 0-based page number.
      required: false
      schema:
        type: integer
        format: int32
        default: 0
    - in: query
      name: page_size
      description: >-
        Number of results per page. Valid values are: 1 - 100. **Default
        value:** 20
      required: false
      schema:
        type: integer
        format: int32
        default: 20
    - in: query
      name: from
      description: Find an environment redirect by its from value
      required: false
      schema:
        type: string
    - in: query
      name: environment_id
      description: >
        An environment's system-defined ID (e.g.,
        12345678-1234-1234-1234-1234567890ab).


        From the Edgio Console, navigate to the desired environment and then
        click **Settings**. It is listed under **Environment ID**.
      required: true
      schema:
        type: string
  security:
    - configScope:
        - app.config
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: >-
              ../components/schemas/Config_V1_Entities_EnvironmentRedirect_Collection.yaml
    '400':
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: ../components/schemas/BaseApi_Entities_UserError.yaml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../components/schemas/BaseApi_Entities_GeneralError.yaml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../components/schemas/BaseApi_Entities_GeneralError.yaml
    '404':
      description: Not Found
      content:
        application/json:
          schema:
            $ref: ../components/schemas/BaseApi_Entities_GeneralError.yaml
    '429':
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: ../components/schemas/BaseApi_Entities_GeneralError.yaml
    '500':
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: ../components/schemas/BaseApi_Entities_GeneralError.yaml
  tags:
    - environment-redirects
  operationId: getConfigV01EnvironmentRedirects
