delete:
  summary: Delete Environment Redirect
  description: Deletes an environment redirect.
  parameters:
    - in: path
      name: environment_redirect_id
      required: true
      schema:
        type: string
  security:
    - configScope:
        - app.config
  responses:
    '204':
      description: OK
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Config_V1_Entities_EnvironmentRedirect.yaml
    '400':
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: ../components/schemas/BaseApi_Entities_UserError.yaml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../components/schemas/BaseApi_Entities_GeneralError.yaml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../components/schemas/BaseApi_Entities_GeneralError.yaml
    '404':
      description: Not Found
      content:
        application/json:
          schema:
            $ref: ../components/schemas/BaseApi_Entities_GeneralError.yaml
    '429':
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: ../components/schemas/BaseApi_Entities_GeneralError.yaml
    '500':
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: ../components/schemas/BaseApi_Entities_GeneralError.yaml
  tags:
    - environment-redirects
  operationId: deleteConfigV01EnvironmentRedirectsEnvironmentRedirectId
get:
  summary: Get Environment Redirect
  description: Returns an environment redirect.
  parameters:
    - in: path
      name: environment_redirect_id
      required: true
      schema:
        type: string
  security:
    - configScope:
        - app.config
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Config_V1_Entities_EnvironmentRedirect.yaml
    '400':
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: ../components/schemas/BaseApi_Entities_UserError.yaml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../components/schemas/BaseApi_Entities_GeneralError.yaml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../components/schemas/BaseApi_Entities_GeneralError.yaml
    '404':
      description: Not Found
      content:
        application/json:
          schema:
            $ref: ../components/schemas/BaseApi_Entities_GeneralError.yaml
    '429':
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: ../components/schemas/BaseApi_Entities_GeneralError.yaml
    '500':
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: ../components/schemas/BaseApi_Entities_GeneralError.yaml
  tags:
    - environment-redirects
  operationId: getConfigV01EnvironmentRedirectsEnvironmentRedirectId
