type: object
properties:
  '@type':
    type: string
    description: The resource's type.
  '@id':
    type: string
    description: The resource's relative path.
  '@links':
    type: object
    description: Links to related resources.
  id:
    type: string
    description: The resource's system-defined ID.
  environment_id:
    type: string
    description: >
      An environment's system-defined ID (e.g.,
      12345678-1234-1234-1234-1234567890ab).


      From the Edgio Console, navigate to the desired environment and then click
      **Settings**. It is listed under **Environment ID**.
  from:
    type: string
    description: The path where to redirect from.
  to:
    type: string
    description: The path where to redirect to.
  status:
    type: integer
    format: int32
    description: 'Redirect status code: 301, 302, 307, 308.'
  forward_query_string:
    type: boolean
    description: Determines whether to forward query string to redirect location.
  created_at:
    type: string
    format: date-time
    description: The environment redirect creation date and time (UTC).
  updated_at:
    type: string
    format: date-time
    description: The environment redirect last modification date and time (UTC).
required:
  - '@type'
  - '@id'
  - id
description: Config_V1_Entities_EnvironmentRedirect model
