required:
  - environment_id
  - hostnames
  - origins
type: object
properties:
  environment_id:
    type: string
  origins:
    $ref: >-
      ../../edgecontrol/schema-base.json#/definitions/property/properties/origins
  hostnames:
    $ref: >-
      ../../edgecontrol/schema-base.json#/definitions/property/properties/hostnames
  rules:
    $ref: ../../edgecontrol/schema-base.json#/definitions/property/properties/rules
  experiments:
    type: array
    description: List of experiments for the configuration.
    example:
      - {}
    items:
      type: string
description: Replace and deploy a complete edge configuration for the given environment
