type: object
properties:
  property_id:
    type: string
    description: The property's system-defined ID.
  name:
    type: string
    description: >
      The environment's name. This name may only consist of lowercase
      characters, numbers, dashes, and underscores.
  can_members_deploy:
    type: boolean
    description: |
      DEPRECATED: use only_maintainers_can_deploy instead."
  only_maintainers_can_deploy:
    type: boolean
    description: >
      Determines whether all organization editors may deploy to this
      environment. Enabling this option restricts deployments to Maintainers and
      the deploy token.
  http_request_logging:
    type: boolean
    description: >-
      Determines whether deep-request inspection for serverless logs will be
      enabled.
required:
  - property_id
  - name
description: Creates an environment.
