name: Deploy to stage
on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed 's/[^[:alnum:].-]/-/g')" >> $GITHUB_ENV

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Node Dependencies
        run: |
          npm install -g linkinator
          yarn install --frozen-lockfile

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install Ruby dependencies
        run: gem install pry json

      - name: Copy API Spec
        env:
          GITLAB_ACCESS_TOKEN: ${{ secrets.GITLAB_ACCESS_TOKEN }}
        run: |
          git clone https://oauth2:$GITLAB_ACCESS_TOKEN@gitlab.com/limelight-networks/cdn-analytics/core/server/eq-metrics-public-api.git
          rsync -av "eq-metrics-public-api/src/api/public-docs/components/" "rest_api/openapi/components"
          rsync -av "eq-metrics-public-api/src/api/public-docs/paths/" "rest_api/openapi/paths"

      - name: Deploy to docs.edg.io (stage)
        run: |
          yarn edgio:deploy --branch=$BRANCH_NAME --token=${{secrets.edgio_prod_deploy_token}} --environment=default
        env:
          GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}

      - name: Run Deployment Manifest Processor
        id: process_manifest
        run: node scripts/workflows/processDeploymentManifest.js

      - uses: jwalton/gh-find-current-pr@v1
        id: finder

      - name: Publish Preview Link
        uses: marocchino/sticky-pull-request-comment@v2.2.0
        with:
          number: ${{ steps.finder.outputs.pr }}
          header: preview
          message: |
            ##### Last deployment (${{ steps.process_manifest.outputs.deployDate }}) 🚀
            Build URL: ${{ steps.process_manifest.outputs.buildUrl }}
            Branch URL: ${{ steps.process_manifest.outputs.branchUrl }}
            Edge URL: ${{ steps.process_manifest.outputs.edgeUrl }}

      - name: Run Link Check
        id: check_links
        run: node scripts/workflows/checkLinks.js ${{ steps.process_manifest.outputs.branchUrl }}

      - name: Read Broken Links Markdown
        id: read_markdown
        run: |
          BROKEN_LINKS=$(cat broken-links.md)
          echo "BROKEN_LINKS=$BROKEN_LINKS" >> $GITHUB_ENV
          echo "timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV
          echo "readable_time=$(date -u +"%Y-%m-%d %H:%M:%S UTC")" >> $GITHUB_ENV

      - name: Upload Linkinator Output
        id: artifact-upload-step
        uses: actions/upload-artifact@v4
        with:
          name: linkinator-output
          path: |
            linkinator-output.json
            broken-links.md

      - name: Comment broken links on PR
        uses: marocchino/sticky-pull-request-comment@v2.2.0
        with:
          number: ${{ steps.finder.outputs.pr }}
          header: broken-links
          message: |
            ##### Broken Links 🚨

            ${{ env.BROKEN_LINKS }}

            👉 [**Download the full report**](../actions/runs/${{ github.run_id }}/artifacts/${{ steps.artifact-upload-step.outputs.artifact-id }}) for a detailed view. 📄

            _Checked at <time datetime="${{ env.timestamp }}">${{ env.readable_time }}</time>_.
